import type { Metadata } from "next";
import { Rubik, Manrope } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Edutech | LMS Platform",
  description: "Generated by Omar Faruque",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${manrope.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
